# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Event
version:      0.507
version_from: Event.pm
installdirs:  site
requires:
    Event:                         0.87
    IO::Handle:                    0
    Test::Simple:                  0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
