---
abstract: 'Tied Filehandles for Nonblocking IO with Object Callbacks'
author:
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
build_requires:
  AnyEvent: 0
  Event: 0
  Test::Simple: 0
  diagnostics: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Event
no_index:
  directory:
    - t
    - inc
requires:
  IO::Handle: 0
  List::MoreUtils: 0
  Time::HiRes: 0
resources:
  repository: http://github.com/muir/File-Flock
version: 0.813
